
export default  [
    'Afghanistan',
    'Akatsuki',
    'Albania',
    'Algeria',
    'Amman',
    'Andorra',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Beijing',
    'Belarus',
    'Belgium',
    'Benin',
    'Bermuda',
    'BlueCountry',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Brasil',
    'Brazil',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cairo',
    'Cameroon',
    'Canada',
    'Candy Kingdom',
    'Catalonia',
    'Cayman Islands',
    'Chechnya',
    'Chile',
    'China',
    'Chinese',
    'Chlenov',
    'Christmas Island',
    'Codeforces',
    'Colombia',
    'CostaRica',
    'Croatia',
    'Cuba',
    'Cuban',
    'Cyprus',
    'Czech Republic',
    'Damascus',
    'Denmark',
    'Djibouti',
    'Dominican Republic',
    'Dsdas',
    'EN',
    'Earth',
    'Ecuador',
    'Egypt',
    'Equestria',
    'Estonia',
    'Ethiopia',
    'Fakeland',
    'Federated States of Micronesia',
    'Finland',
    'France',
    'GDL',
    'Gabon',
    'Galicia',
    'Gensokyo',
    'Georgia',
    'Germany',
    'Gggga',
    'Ghana',
    'Giza',
    'Greece',
    'Haiti',
    'Honduras',
    'HongKong',
    'Hubei',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Japan',
    'Japanistan',
    'Jenabe Haghani Jahamitam',
    'Jordan',
    'Karp-ChantCountry',
    'Kazakhstan',
    'Kenya',
    'Key',
    'Kireston',
    'Korea',
    'Republicof',
    'Korea',
    'DPR',
    'Krakozya',
    'Kyrgyz',
    'Kyrgyzstan',
    'LOLIDONTKNOW',
    'La Réunion',
    'La royaume du KODIA',
    'Land of Ooo',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lithuania',
    'Luxembourg',
    'Macau',
    'Macedonia',
    'Madagascar',
    'Malaysia',
    'Marsplanet',
    'Mauritius',
    'Mete',
    'Mexico',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Morroco',
    'Mouood',
    'Tehran',
    'Iran',
    'Mozambique',
    'NSOI',
    'Nada',
    'Nepal',
    'NewZealand',
    'Nicaragua',
    'Nigeria',
    'Nirvana',
    'Norway',
    'Oman',
    'PRC',
    'Pakistan',
    'Palestine',
    'Paraguay',
    'Peru',
    'Philippines',
    'PokemonCenter',
    'Poland',
    'Portugal',
    'PuertoRico',
    'Qatar',
    'RF',
    'Rff',
    'Romania',
    'Russia',
    'Rwanda',
    'Rysaldystan',
    'S.Korea',
    'SaudiArabia',
    'Sdyu',
    'Sea',
    'Serbia',
    'Singapore',
    'SkyDynasty',
    'Slovakia',
    'Slovenia',
    'South Africa',
    'Spain',
    'SriLanka',
    'Sudan',
    'Survivier',
    'Sweden',
    'Switzerland',
    'Syria',
    'Tabulistan',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Tatooine',
    'Tehran',
    'TerranDominion',
    'Thailand',
    'The Netherlands',
    'The PacificOcean',
    'The people\'s republicof CJ',
    'Third Reich',
    'Tierradelaraja',
    'Togo',
    'Tunisia',
    'Tunisie',
    'Turkey',
    'Turkiye',
    'Turkmenistan',
    'UAE',
    'UK',
    'Ukraine',
    'United Kingdom',
    'United States (USA)',
    'Uruguay',
    'Uzbekistan',
    'Valencian Country',
    'Vatican',
    'Venezuela',
    'Vietnam',
    'Westeros',
    'Yakhchiabad',
    'Yanghong',
    'Yemen',
    'Zambia',
    'Zimbabwe'
];
